---
- name: Install minecraftserver
  ansible.builtin.include_tasks: 
    file: install.yml
  when: >
    minecraftserver_state is not defined
    or minecraftserver_state == 'present'

- name: Remove minecraftserver
  ansible.builtin.include_tasks: 
    file: remove.yml
  when: >
    minecraftserver_state is defined
    and minecraftserver_state == 'absent'
