---
- name: create docker working directory
  file:
    path: "{{ minecraftserver_docker_working_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ minecraftserver_docker_compose_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart minecraftserver service

- name: Create systemd unit file
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ minecraftserver_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart minecraftserver service

- name: create data volume directory
  file:
    path: "{{ minecraftserver_data_volume_directory }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: 0750
