---
- name: Install minecraftserver
  include: install.yml
  when: >
    minecraftserver_state is not defined
    or minecraftserver_state == 'present'

- name: Remove minecraftserver
  include: remove.yml
  when: >
    minecraftserver_state is defined
    and minecraftserver_state == 'absent'
