---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/default/requirements.yml

driver:
  name: vagrant
  provider:
    name: libvirt

platforms:
  - name: ansible-minecraft-focal
    box: generic/ubuntu2004

provisioner:
  name: ansible
  playbooks:
    prepare: ../state-absent-force-remove-persistent-data/prepare.yml
    converge: ../state-absent-force-remove-persistent-data/converge.yml
    verify: ../state-absent-force-remove-persistent-data/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
